"""Add Ticket status

Revision ID: 0f12b5bcd907
Revises: b0b1a5adbefb
Create Date: 2023-01-18 17:45:15.759213

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql



# revision identifiers, used by Alembic.
revision = '0f12b5bcd907'
down_revision = 'b0b1a5adbefb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        status = postgresql.ENUM('new', 'progress', 'resolved', name='status')
        status.create(op.get_bind())
        batch_op.add_column(sa.Column('status', sa.Enum('new', 'progress', 'resolved', name='status'), server_default='new', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('status')
        status = postgresql.ENUM('new', 'progress', 'resolved', name='status')
        status.drop(op.get_bind())

    # ### end Alembic commands ###
