"""Initial migration.

Revision ID: 80450e7be74c
Revises: 
Create Date: 2023-01-17 01:00:49.132804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80450e7be74c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
